name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.1.0
  flutter_svg: ^2.0.9
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0
  dio: ^5.9.1
  retrofit: ^4.9.2
  get_it: ^9.2.0
  logger: ^2.6.2
  mocktail: ^1.0.4
  injectable: ^2.7.1+4
  bloc_concurrency: ^0.3.0
  stream_transform: ^2.1.1

dev_dependencies:
  build_runner: ^2.11.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.5
  injectable_generator: ^2.12.0
  json_serializable: ^6.12.0
  retrofit_generator: ^10.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/image/
